const fixedAccounts = [
  {
    accountName: 'Sales Discount',
    accountType: 'income',
    currency: 'AED',
    description:
      'Any reduction on your selling price as a discount can be recorded into the discount account.',
    accountCode: 'AC-INC-03',
    parentAccount: 'Income',
    fixed: true,
  },
  {
    accountName: 'Product Purchase',
    accountCode: 'AC-EX-01',
    accountType: 'expense',
    currency: 'AED',
    description: '',
    parentAccount: 'Expense',
    fixed: true,
  },
  {
    accountName: 'Sales',
    accountType: 'income',
    accountCode: 'AC-SL',
    currency: 'AED',
    description: 'Any sales income is recorded into the sales account.',
    parentAccount: 'Income',
    fixed: true,
  },
  {
    accountName: 'Late Fee Income',
    accountType: 'income',
    accountCode: 'AC-INC-02',
    currency: 'AED',
    description:
      'Any late fee income is recorded into the late fee income account. The late fee is levied when the payment for an invoice is not received by the due date.',
    parentAccount: 'Income',
    fixed: true,
  },
  {
    accountName: 'Shipping Charge',
    accountType: 'income',
    currency: 'AED',
    accountCode: 'AC-INC-04',
    description:
      'Shipping charges made to the invoice will be recorded in this account.',
    parentAccount: 'Income',
    fixed: true,
  },
  {
    accountName: 'Input VAT',
    accountType: 'currentasset',
    accountCode: 'AC-CA-02',
    currency: 'AED',
    description: 'The amount of money charged to you as VAT on your purchases.',
    parentAccount: 'Current Asset',
    fixed: true,
  },
  {
    accountName: 'Petty Cash Account',
    accountType: 'cashandbank',
    currency: 'AED',
    accountCode: 'AC-PC-01',
    description:
      'It is a small amount of cash that is used to pay your minor or casual expenses rather than writing a check.',
    parentAccount: 'Cash in Hand',
    fixed: true,
  },
  {
    accountName: 'Inventory Asset',
    accountType: 'stock',
    accountCode: 'AC-INV-ST',
    currency: 'AED',
    description:
      'An account which tracks the value of goods in your inventory.',
    parentAccount: 'Inventory Stock',
    fixed: true,
  },
  {
    accountName: 'Goods',
    accountType: 'stock',
    accountCode: 'AC-INV-FG',
    currency: 'AED',
    description: 'An account which tracks the value of finished goods.',
    parentAccount: 'Inventory Stock',
    fixed: true,
  },
  {
    accountName: 'Consumables',
    accountType: 'stock',
    accountCode: 'AC-INV-CS',
    currency: 'AED',
    description: 'An account which tracks the value of consumable products.',
    parentAccount: 'Inventory Stock',
    fixed: true,
  },
  {
    accountName: 'Materials',
    accountType: 'stock',
    accountCode: 'AC-INV-MT',
    currency: 'AED',
    description: 'An account which tracks the value of material products.',
    parentAccount: 'Inventory Stock',
    fixed: true,
  },
  {
    accountName: 'Output VAT',
    accountType: 'currentliability',
    accountCode: 'AC-CL-OV',
    currency: 'AED',
    description: 'The amount of money charged as VAT on your sales.',
    parentAccount: 'Current Liability',
    fixed: true,
  },
  {
    accountName: 'Salary and wages',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-EX-03',
    description:
      'Salaries for your employees and the wages paid to workers are recorded under the salaries and wages account.',
    parentAccount: 'Salary and Wages',
    fixed: true,
  },
  {
    accountName: 'Salary Payable',
    accountType: 'currentliability',
    currency: 'AED',
    accountCode: 'AC-CL-SP',
    description:
      'Salaries for your employees and the wages paid to workers are recorded under the salaries and wages account.',
    parentAccount: 'Current Liability',
    fixed: true,
  },
  {
    accountName: 'Employee Advance',
    accountType: 'currentasset',
    currency: 'AED',
    accountCode: 'AC-CA-03',
    description:
      "Money paid out to an employee in advance can be tracked here till it's repaid or shown to be spent for company purposes.",
    parentAccount: 'Current Asset',
    fixed: true,
  },
  {
    accountName: 'Employee Loan',
    accountType: 'currentasset',
    currency: 'AED',
    accountCode: 'AC-CA-04',
    description:
      "Money paid out to an employee as a loan can be tracked here till it's repaid or shown to be spent for company purposes.",
    parentAccount: 'Current Asset',
    fixed: true,
  },
  {
    accountName: 'Prepaid Expenses',
    accountType: 'currentasset',
    currency: 'AED',
    accountCode: 'AC-CA-05',
    description:
      "Money paid out for expenses that are not yet due can be tracked here till it's repaid or shown to be spent for company purposes.",
    parentAccount: 'Current Asset',
    fixed: true,
  },
  {
    accountName: 'VAT Payable',
    accountType: 'currentliability',
    accountCode: 'AC-CL-VP',
    currency: 'AED',
    description: 'The amount of VAT which you owe.',
    parentAccount: 'Current Liability',
    fixed: true,
  },
  {
    accountName: 'VAT Receivable',
    accountType: 'currentasset',
    accountCode: 'AC-CA-04',
    currency: 'AED',
    description: 'The amount of VAT which you are owed.',
    parentAccount: 'Current Asset',
    fixed: true,
  },
  {
    accountName: 'Employee Reimbursements',
    accountType: 'currentliability',
    accountCode: 'AC-CL-ER',
    currency: 'AED',
    description:
      'This account can be used to track the reimbursements that are due to be paid out to employees.',
    parentAccount: 'Current Liability',
  },
  {
    accountName: 'Retained Earnings',
    accountType: 'ownersequity',
    accountCode: 'AC-EQ-RE',
    currency: 'AED',
    description:
      'The earnings of your company which are not distributed among the share holders is accounted as retained earnings.',
    parentAccount: 'Retained-Earnings',
    fixed: true,
  },
  {
    accountName: 'Drawings',
    accountType: 'ownersequity',
    accountCode: 'AC-EQ-DR',
    currency: 'AED',
    description:
      'The money withdrawn from a business by its owner can be tracked with this account.',
    parentAccount: 'Capital Account',
    fixed: true,
  },
  {
    accountName: 'Capital Account',
    accountType: 'ownersequity',
    accountCode: 'AC-EQ-CA',
    currency: 'AED',
    description:
      'The money with which the business was started can be tracked with this account.',
    parentAccount: 'Capital Account',
    fixed: true,
  },
  {
    accountName: 'Other Reserves',
    accountType: 'ownersequity',
    accountCode: 'AC-EQ-RS',
    currency: 'AED',
    description:
      'The money with which the business was started can be tracked with this account.',
    parentAccount: 'Reserves',
    fixed: true,
  },
  {
    accountName: 'Bank Account',
    accountType: 'cashandbank',
    currency: 'AED',
    accountCode: 'AC-BK-01',
    description: '',
    parentAccount: 'Bank Accounts',
    fixed: true,
  },
  {
    accountName: 'Equipments',
    accountType: 'fixedasset',
    currency: 'AED',
    accountCode: 'AC-FA-01',
    description: '',
    parentAccount: 'Fixed Asset',
    fixed: true,
  },
  {
    accountName: 'Vehicles',
    accountType: 'fixedasset',
    currency: 'AED',
    accountCode: 'AC-FA-02',
    description: '',
    parentAccount: 'Fixed Asset',
    fixed: true,
  },
  {
    accountName: 'Goods Purchase',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-PP-01',
    description: '',
    parentAccount: 'Product Purchase',
    fixed: true,
  },
  {
    accountName: 'Vehicle Purchase',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-PP-02',
    description: '',
    parentAccount: 'Product Purchase',
    fixed: true,
  },
  {
    accountName: 'Equipment Purchase',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-PP-03',
    description: '',
    parentAccount: 'Product Purchase',
    fixed: true,
  },
  {
    accountName: 'Consumable Purchase',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-PP-04',
    description: '',
    parentAccount: 'Product Purchase',
    fixed: true,
  },
  {
    accountName: 'Material Purchase',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-PP-05',
    description: '',
    parentAccount: 'Product Purchase',
    fixed: true,
  },
  {
    accountName: 'Transfer fees',
    accountType: 'expense',
    accountCode: 'AC-BC-01',
    currency: 'AED',
    description: '',
    parentAccount: 'Bank Charges',
  },
  {
    accountName: 'VAT Charge',
    accountType: 'expense',
    accountCode: 'AC-BC-02',
    currency: 'AED',
    description: '',
    parentAccount: 'Bank Charges',
  },
];

const fixedParentAccounts = [
  {
    accountName: 'Other Current Asset',
    accountType: 'othercurrentasset',
    accountCode: 'AC-OA',
    currency: 'AED',
    description:
      'Other current assets are assets that are not cash or bank accounts.',
    fixed: true,
  },
  {
    accountName: 'Current Asset',
    accountType: 'currentasset',
    accountCode: 'AC-CA',
    currency: 'AED',
    description:
      'Current assets are assets that are expected to be converted into cash or used up within one year.',
    fixed: true,
  },
  {
    accountName: 'Cash in Hand',
    accountType: 'cashandbank',
    currency: 'AED',
    accountCode: 'AC-PC',
    description:
      'It is a small amount of cash that is used to pay your minor or casual expenses rather than writing a check.',
    fixed: true,
  },
  {
    accountName: 'Bank Accounts',
    accountType: 'cashandbank',
    currency: 'AED',
    accountCode: 'AC-BK',
    description:
      'Bank accounts are used to track the money in your bank accounts.',
    fixed: true,
  },
  {
    accountName: 'Fixed Asset',
    accountType: 'fixedasset',
    currency: 'AED',
    accountCode: 'AC-FA',
    description:
      'Fixed assets are long-term assets that are used in the business for a long time.',
    fixed: true,
  },
  {
    accountName: 'Stock',
    accountType: 'stock',
    accountCode: 'AC-ST',
    currency: 'AED',
    description:
      'An account which tracks the value of goods that are currently fed into production.',
    fixed: true,
  },
  {
    accountName: 'Inventory Stock',
    accountType: 'stock',
    accountCode: 'AC-INV-ST',
    currency: 'AED',
    description:
      'An account which tracks the value of goods that are currently in stock.',
    fixed: true,
  },
  {
    accountName: 'Other Current Liability',
    accountType: 'othercurrentliability',
    accountCode: 'AC-OCL',
    currency: 'AED',
    description:
      'Other current liabilities are liabilities that are not cash or bank accounts.',
    fixed: true,
  },
  {
    accountName: 'Long term Liability',
    accountType: 'longtermliability',
    accountCode: 'AC-LTL',
    currency: 'AED',
    description:
      'Long term liabilities are liabilities that are not due within one year.',
    fixed: true,
  },
  {
    accountName: 'Current Liability',
    accountType: 'currentliability',
    accountCode: 'AC-CL',
    currency: 'AED',
    description:
      'Current liabilities are liabilities that are due within one year.',
    fixed: true,
  },
  {
    accountName: "Owner's Equity",
    accountType: 'ownersequity',
    currency: 'AED',
    accountCode: 'AC-EQ',
    description:
      "The owners rights to the assets of a company can be quantified in the owner''s equity account.",
    fixed: true,
  },
  {
    accountName: 'Capital Account',
    accountType: 'ownersequity',
    accountCode: 'AC-CA',
    currency: 'AED',
    description:
      'The capital account is the account that tracks the money that the owners have invested in the business.',
    fixed: true,
  },
  {
    accountName: 'Reserves',
    accountType: 'ownersequity',
    accountCode: 'AC-DR',
    currency: 'AED',
    description:
      'The reserves account is the account that tracks the money that the owners have invested in the business.',
    fixed: true,
  },
  {
    accountName: 'Retained-Earnings',
    accountType: 'ownersequity',
    accountCode: 'AC-RE',
    currency: 'AED',
    description:
      'The retained earnings account is the account that tracks the money that the owners have invested in the business.',
    fixed: true,
  },
  {
    accountName: 'Income',
    accountType: 'income',
    accountCode: 'AC-INC',
    currency: 'AED',
    description:
      'A general category of account where you can record any income which cannot be recorded into any other category.',
    fixed: true,
  },
  {
    accountName: 'Other Income',
    accountType: 'income',
    currency: 'AED',
    accountCode: 'AC-OIN',
    description:
      'Other income is income that is not directly related to the primary business operations.',
    fixed: true,
  },
  {
    accountName: 'Indirect Income',
    accountType: 'income',
    currency: 'AED',
    accountCode: 'AC-INEN',
    description:
      'Indirect income is income that is not directly related to the primary business operations.',
    fixed: true,
  },
  {
    accountName: 'Expense',
    accountCode: 'AC-EX',
    accountType: 'expense',
    currency: 'AED',
    description: '',
    fixed: true,
  },
  {
    accountName: 'Product Purchase',
    accountCode: 'AC-PP',
    accountType: 'expense',
    currency: 'AED',
    description: '',
    fixed: true,
  },
  {
    accountName: 'Cost of Goods Sold',
    accountType: 'costofgoodssold',
    accountCode: 'AC-COG',
    currency: 'AED',
    description: 'An expense account which tracks the value of the goods sold.',
    fixed: true,
  },
  {
    accountName: 'Other Expenses',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-OTE',
    description:
      'Any minor expense on activities unrelated to primary business operations is recorded under the other expense account.',
    fixed: true,
  },
  {
    accountName: 'Indirect Expense',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-INEX',
    description:
      'Indirect expense is expense that is not directly related to the primary business operations.',
    fixed: true,
  },
  {
    accountName: 'Salary and Wages',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-SW',
    description:
      'Salary and wages are expense that is not directly related to the primary business operations.',
    fixed: true,
  },
  {
    accountName: 'Bank Charges',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-BC',
    description:
      'Bank charges are expense that is not directly related to the primary business operations.',
    fixed: true,
  },
  {
    accountName: 'GOV Charges',
    accountType: 'expense',
    currency: 'AED',
    accountCode: 'AC-GC',
    description:
      'Government charges are expense that is not directly related to the primary business operations.',
    fixed: true,
  },
  {
    accountName: 'Accounts Payable',
    accountType: 'currentliability',
    accountCode: 'AC-CL-AP',
    currency: 'AED',
    description:
      'This is an account of all the money which you owe to others like a pending bill payment to a vendor,etc.',
    fixed: true,
  },
  {
    accountName: 'Accounts Receivable',
    accountType: 'currentasset',
    accountCode: 'AC-CA-01',
    currency: 'AED',
    description:
      'The money that customers owe you becomes the accounts receivable. A good example of this is a payment expected from an invoice sent to your customer.',
    fixed: true,
  },
];

module.exports = { fixedAccounts, fixedParentAccounts };
